### ISSUE TITLE
关于“武汉市开展全民核酸检测”一事的思考

### ISSUE THREAD

**Issue by ghost** [qxnatalie/Learn_ConsumerBehaviour#4]
5.12日，武汉开展了全民核酸检测。
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？

**Comment by qxnatalie** [comment]
大家第一个“自创”话题，我先抢个沙发。

在整个全民核酸检测活动结束后，会产生行为学的**框架效应** *framing effect*。对于接受检测的市民，会有**禀赋效应** *endowment effect*发生。其他方面，请大家可以结合任何一点来展开说明。

**Comment by qiudi666** [comment]
1.我认为政府主要是从疫情防控、经济、政治、社会治安等层面进行综合考虑，从而颁布并积极推进此项政策。就经济和社会治安层面来说，武汉市对无症状感染者进行全面排查，降低了复工复产的风险，消除了大部分市民不安的情绪，有利于武汉经济快速复苏，市民生活回到常态。
2.框架效应是指一个问题两种在逻辑意义上相似的说法却导致了不同的决策判断。从武汉市市民角度来看，全民核酸检测是受益的，不花一分钱就可以消除从疫情爆发以来到检测前的忧虑，如果身边有患者还可尽量降低潜在感染风险，旅游、聚餐等消费行为可能会有一定的增加。从非武汉市市民的角度来看，武汉市核酸核酸检测是有损失的，以金额来衡量的话，那么就是损失了核酸检测的市价。对于这部分人来说，如果想要尽快消除心中的疑虑和担忧，只能花几百块去医院做检测，如果自己不是无症状感染者，就相当于损失了几百块。
3.我认为此政策对热爱运动的老年群体影响比较大。他们的免疫力相对于年轻人来说比较低，容易患病，在家中闲不住，喜欢做户外运动。在武汉疫情被控制到全民核酸检测期间，作为家中的长辈，他们被晚辈劝导不要放松警惕，没有要紧事不要出门，小心被无症状感染者传染，无奈继续宅在家中，无法进行户外运动。而在排查了无症状感染者后，禁止他们出门的阻力已经变得很小了，广场舞、骑行、太极等团体陆续开展活动，与之相关的消费行为（如舞服、场地费、报名费等）也会越来越多。

**Comment by Riley-Ai** [comment]
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策。
答：政府主要是从疫情防控、经济、政治、社会治安等层面进行综合考虑。目的是：第一，进行全员排查，找出潜在患者；第二，增强社会信心，让武汉人民放心大胆地“走出去"；第三，主要是为了促进复工复产。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
答：从武汉市市民角度来看，全民核酸检测是受益的，免费做检测消除内心对自己患病的担忧，降低潜在感染风险，线下消费行为可能会有一定的增加。从非武汉市市民的角度来看，需要自己花几百块去医院做检测，如果自己不是无症状感染者，就损失了几百块，还会觉得不公平。
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？
答：主流文化群体会认为进行武汉全员核酸检测是保障居民自身安全的手段，更是为了维护大多数人群的健康。但是亚文化群体可能会认为如果一个人并没有患病，但政府却要求其进行核酸检测，在他们看来可能会侵犯了人权。

**Comment by Tiantian-Wu** [comment]
1、当前全市疫情防控形势趋于平稳，但每日仍有新发现的无症状感染者，影响在汉、返汉人员正常工作生活的信心。为统筹疫情防控和经济社会发展，为复工复产、复商复市、复学复课营造安全健康的学习、生产、生活环境，市委、市政府在全市范围内进一步加强核酸检测、加快筛查无症状感染者，最大限度地摸清无症状感染者底数，实行全流程严格闭环管理，全力阻断可能的传染源。这样做既有利于精准防控，力争早日阻断病毒传播，又有利于消除社会恐惧和偏见，让广大居民更放心安心，也有利于促进经济社会全面恢复，使生活秩序回归常态。
2、禀赋效应是指当个人一旦拥有某项物品，那么他对该物品价值的评价要比未拥有之前大大增加。这一现象可以用行为金融学中的“损失厌恶”理论来解释，该理论认为一定量的损失给人们带来的效用降低要多过相同的收益给人们带来的效用增加。因此人们在决策过程中对利害的权衡是不均衡的，对“避害”的考虑远大于对“趋利”的考虑，所以失去的和得不到的都会格外珍惜。武汉市民在疫情期间承受了几个月的恐慌，所以确定自己不是无症状感染者就显得尤为重要，况且市政府免费提供的，可以看到，绝大多数武汉市民都对此次检测持欢迎态度。经过检测后。武汉人民可以重新开启全民安全感，重拾久违的宁静和快乐，会对在疫情期间不能做的事情表现出格外的热情，所以在一定程度上可以刺激消费。非武汉的市民，虽然武汉已经解封，但心中对武汉仍然是不放心的，这次的全民核酸检测在一定程度上也可以消除他们对武汉的疑虑。
3、对于那些目前仍对疫情持恐慌忧虑态度的人或者是由于疫情对自己工作造成了较大影响的人会觉得全民检测很有必要，而对于那些已经对疫情放松警惕并开始正常生活的人来说，会觉得全民检测有些多此一举。对于一些兴趣活动团体来说，这次的全面检测也给他们正常开展活动提供了依据和动力，可以促进餐饮、服务、艺术培训等相关产业的发展。

**Comment by xsyAriel** [comment]
1.政府采取全民核酸检测综合考虑了政治，经济，文化等多个因素，但是从消费者行为学的角度来说，我认为最大的原因是增强消费者的消费欲望。在武汉解封后，市民逐渐复工，生活开始回到正轨，武汉政府也开始通过发放消费卷刺激消费，可是还是一直有无症状的感染者被发现，在这种情况下，消费者仍旧会对感染有担忧，外出娱乐和餐饮堂食的市场短期内无法恢复正常。同时武汉的消费者受疫情影响大，仍旧会担忧疫情卷土卷土重来，对预期收入持消极态度，所以消费行为也会减少。
2.对于接受核酸检测的武汉市民，全民核酸检测可以有效降低消费者对于风险的感知，从禀赋效应来看，消费者对于“避害”的考虑远大于对“趋利”的考虑。消费者出于对损失的畏惧和对于预期收入的不确定，消费者会减少购物行为和投资行为等，整个城市的恢复都会受到这种”避害“心理的影响。
对于非武汉市民来说，对于在进行与武汉有关的消费行为时，影响会更大，在进行与武汉无关的消费行为时，全民核酸可以带来积极的市场环境，消费者会保持乐观的心态，购物行为会有一定提升。在进行与武汉有关的消费时，全民核酸显示的确定的无感染病毒，消费者对于感染的担忧会减少，消费行为会有较大程度的提升。
3.对于主流文化群体来说，全民核酸可以有效减少感知风险，加快城市恢复正常，市民的生活也能尽快恢复正常。对于部分亚文化群体，可能会认为全民核酸检测侵犯了他的自由，他有选择不进行检测的权利。

**Comment by DR-ng** [comment]
1、政府部门从政治、经济和文化的角度考虑，开展武汉全民核酸检测。作为新冠肺炎疫情的爆发区，武汉经济受到很大损失。现在复工复产，增加消费很重要，但是不论是武汉的居民还是其他地区的居民还是会因为疫情，尤其是突然出现的无症状感染者而有所担忧，害怕有很大的风险会被感染，所以这次核酸检测不仅是为了公共安全，也是为了更快恢复正常的生产生活，减少人们的担忧、增加人们信心投入正常的生活中从而促进消费、促进经济的复苏。
2、禀赋效应是指当一个人拥有某种物品，那么他对物品价值的评价要比未拥有之前大大增加。核酸检测过后，武汉市民会减少担忧、加强了信心投入复工复产的生活，人员流动加大，消费行为也会增多尤其是线下消费行为。
3、能够加快学生群体返校复学，各行工作人员也能快速投入工作中，老年人的各种娱乐活动也会大大增加。总的来说就是市民回到正常的生活状态，消费行为更会大大增加。

**Comment by Zhuying000** [comment]
5.12日，武汉开展了全民核酸检测。
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策。
   政府部门从公关卫生安全、经济和政治的角度考虑，开展了全民核酸检测。因为武汉作为最后解封、疫情也最为严重的地区，全民检测有助于保证城市安全，保障复工复产和经济的复苏。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
 全民核酸检测对于武汉市民来说，有助于检测出无症状感染者，保证他们的安全，稳定武汉市民的情绪，减少他们的担忧。 免费的检测可以让每个人都能享受，减少他们的经济压力。
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？
  现在武汉主要的群体有学生人群、工作人群、老年人群等，此政策对于各个群体来说都是有益的，有助于学生和工薪人群尽快复学复工，对于老年人来说也可以让他们更好地娱乐和生活。

**Comment by Happy-deep** [comment]
1.	政府主要是为了疫情防控，社会治安方面等综合考虑。全民核酸检测的目的是①全排查携带者进行及时隔离治疗防止病毒扩散②有效安抚了处于恐慌的民心，增强社会信心③为恢复经济提供安全的环境，促进复工复产。这项政策有利于早日防止病毒再传播，消除社会恐惧，平定民心，使生活秩序回归常态。
2.	禀赋效应或厌恶剥夺(英语：Endowment effect)，形容当一个人拥有某项物品或资产的时候，他对该物品或资产的价值评估要大于没有拥有这项物品或资产的时候。由于禀赋效应，人们在进行决策时往往趋向于风险规避，对于“避害”的需求要远高于“趋利”。因此全民核酸检测政策实施时，武汉市民能够积极接受，愿意牺牲时间、精力等成本去配合。并且在核酸检测结果出来之后，消费者心理防线放松下来，逐渐提升消费需求。对于非武汉市民来说，此措施能够减少对武汉市民和武汉的忧虑，对与武汉相关的消费行为产生积极影响。
3.	由于受到不同文化的影响，处于不同文化环境的群体所受到的影响是不一样的。例如老年人群体，通过核酸检测能够让其安心恢复其正常的生活；学生群体，进行安全的复学。

**Comment by bulebuleaa** [comment]
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策。
武汉政府开展全民检测是基于疫情防控、经济恢复、政治、社会安全稳定的角度考虑的。全民检测的主要目的是全面排查出病毒携带者，加强疫情的防治。从消费者角度来讲，这次全民检测有利于消除恐慌，促进复工复产，推动消费，促进经济恢复。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
禀赋效应是指当个人一旦拥有某项物品，那么他对该物品价值的评价要比未拥有之前大大增加。全民核酸检测对武汉市民会产生禀赋效应。武汉市民认为这一政策对他们来说是收益的，会对这个政策产生积极的评价，同时检测结果会恢复他们的信心，使他们愿意消费。框架效应框架效应是指一个问题两种在逻辑意义上相似的说法却导致了不同的决策判断。也就是指：当消费者感觉某一价格带来的是“损失”而不是“收益”时，他们对价格就越敏感。对于非武汉市民而言，这个政策会产生框架效应，非武汉市民不能免费享受这个服务，可能会产生负面情绪。
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？
这个政策对武汉不同群体会造成不同的影响。对工人群体来说，他们可以最大程度的复工，对学生群体而言，可以推动复学。

**Comment by Faolan-SY** [comment]
1.自从疫情爆发以来，武汉一直是重灾区，不仅武汉市民感到恐慌、情绪低落，同时其他地区的人也对从武汉地区过去的人有所排斥，由此造成了武汉市民内心的不平衡，武汉市民渴望证明自己，获得和他人一样的待遇。
2.全民核酸检测让武汉市民能够免费接受检测，多了一份保障，同时全民核酸检测能够检测出人群中的无症状感染者，对武汉市中的感染者进行了进一步的筛查，将感染者进行隔离治疗后，对于武汉市民的情绪有了很大的提升，提高了武汉市民的斗志，让武汉市民对于疫情的全面恢复多了一些期待。对非武汉市市民来说，武汉全民核酸检测能够逐渐改变他们对武汉地区人们的看法，减少了偏见，也让他们对疫情的全面恢复多了几分信心。
3.此政策，对于主流群体来说是一道福音，他们期望已久，并会积极配合，对于工人群体来说，他们对于工作的积极性会大大提升，对于学生和老师群体来说，这对学校的早日复学有着很大的帮助。

**Comment by huangyanfang00** [comment]
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策？
基于各种因素考虑，虽然疫情防控形势趋于平稳，但无症状感染者仍在出现，牵动着在汉甚至全中国的心弦。全民核酸检测可以为为统筹疫情防控和经济社会发展，为复工复产、复商复市、复学复课营造安全健康的学习、生产、生活环境，加快筛查无症状感染者，最大限度地摸清无症状感染者底数，全力阻断可能的传染源。这样的精准防控也有利于消除社会恐惧和偏见，让人们对武汉对中国更有信心。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
武汉市民通过全民核酸检测消费者出于对损失的厌恶和对于自身健康状况的不确定，消费者态度相对也比较消极，消费行为也就受禀赋效应的影响，赋效应是指当个人一旦拥有某项物品，那么他对该物品价值的评价要比未拥有之前大大增加。武汉市民在全民核酸后，确认自身的状况对之后的生活更有信心。
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？
大部分社会群体成员应该为武汉进行全名核酸检测表示支持并觉得必要，但是亚文化群体可能觉得武汉之外的群体也应得到重视。

**Comment by promisecret** [comment]
1.政府从政治、经济，社会等角度出发，对武汉市全体市民开展核酸检测，排查无症状感染者。这项举措可以让武汉市民真正地放心，消除对身边无症状感染者的疑虑。武汉复工复产也需要排查做保障。
2.免费核酸检测对武汉市民来说，大大地提升了市民的信心，大家可以放心地走出家门，进行正常的社会活动。对于非武汉市市民来说，他们以后也可以更加放心地去武汉工作或者旅游，但对于免费检测，可能部分人会有异议。
3.对于工人群体，核酸检测有利于复工复产；对于学生群体，有利于复学；对于老年群体，有利于早些出门活动。

**Comment by yeahhuinim** [comment]
1.你觉得政府为什么要开展全民检测呢？尝试用消费者行为学的理论体系来解读政府这个政策。
我认为是政府在综合各方面考虑后作出的决定。当前的疫情已得到了初步控制，但无症状感染者依旧存在。通过全民检测，全面排查无症状感染者，对于出现的情况及时的应对处理，更进一步控制疫情。
2.到目前为止，全民核酸检测对武汉市市民的行为造成了什么样的影响呢？对非武汉市市民行为（以及态度）造成了什么样的影响呢？
对武汉市市民来说，很大程度上消除了居民的恐慌，能够比较安心的外出进行各类活动；
对于非武汉市市民来说，破除他们的偏见。但同时他们也会产生为什么武汉市民免费检测但自己却要自费检测的不平衡心理。
3.目前我们已经学习了消费者行为学中“文化”与“亚文化”这些因素，尝试讨论此政策对不同群体会造成哪些不同影响？
对于上班族来说，利于尽快的复工复产，恢复正常工作；对于学生族来说，利于复学。

**Comment by akabula** [comment]
1.武汉市开始对全市居民进行核酸检测，主要是为了排查无症状感染者，通过核酸检测后，不仅可以让武汉市民放心，也是希望其他人不要对武汉存在偏见，这既有利于精准防控，保护群众健康，又有助于人员的合理流动、推动社会经济和生活秩序的全面恢复。
2.对于武汉市民来说，进行全民核算检测可以让每一位市民对健康问题放心，顺利进行返工复学。
  对于非武汉市市民来说，可以让他们对“武汉”的态度进行转变，但可能也会出现不平衡的心理，如为什么武汉市民可以免费检测而自己不行。
3.对于上班族来说，利于尽早地复工复产，恢复正常工作；对于学生族来说，利于复学，早日回到校园；对于老人来说，利于出门进行休闲娱乐活动。

**Comment by Rena-99** [comment]
1、为了进一步明确疫情的范围，开展主动搜索，加强检测和排查的力度，扩大检测范围也是落实“四早措施”的重要举措，也是统筹推进复工复产复学和做好常态化防控的重要保障。在对疫情风险、检测能力进行全面科学评估的基础上，扩大核酸检测的范围，既有利于精准防控，保护群众健康，又有助于人员的合理流动、推动社会经济和生活秩序的全面恢复。立足更精准更有效地防，优化完善疾病预防控制机构职能设置，创新医防协同机制，强化各级医疗机构疾病预防控制职责，督促落实传染病疫情和突发公共卫生事件报告责任，健全疾控机构与城乡社区联动工作机制，加强乡镇卫生院和社区卫生服务中心疾病预防控制职责，夯实联防联控的基层基础。
2、对于接受核酸检测的市民，可以安抚市民的情绪，消费者也会保持积极乐观的心态来进行消费活动，对于感染的担忧就会减少，复工复产的进度会加快，消费行为会增多。
3、文化对不同人产生的影响也不同。学生复学，青壮年复工，老年人恢复日常休闲娱乐活动。

**Comment by addition-nzr** [comment]
1.开展全民核酸检测是为了保复工复产的顺利进行，因为肺炎爆发的周期性，在每一个爆发周期的始末都要进行一次人数清查，以便于统计相关数据，恢复经济发展和人员安排。
2.造成的影响：对于武汉本市市民大多积极服从检测，本着故土情怀也大多会积极配合，百姓检测完容易放心下来；对于武汉外来人口容易造成不良影响，因为务工的较多，检测不仅会工时造成影响，还会因为可能会被遣返的原因担惊受怕，容易采取猜疑的态度对待检测，支持人数不比本市市民比例高。
3.文化与亚文化角度下，人员聚集的活动大受打击，而对人手要求低的产业恢复较快，自动化生产企业的员工和线上工作的职员基本未受到波及。人们的日常生活也是，菜市场、公共交通、集会不能运作，从事这方面的劳动者受损较大。

**Comment by Ashley-SKY** [comment]
1、全民核酸检验加强了检测和排查的力度，能够发现更多的无症状感染者，既有利于精准防控，维护群众健康，又有助于人员合理流动、推动全面复工复产，学校复学，促进社会经济和生活秩序的全面恢复。
2、对于武汉本市市民来说他们基本都会积极服从检测，检测完后对于感染的担忧就会减少，可以对健康问题放心，复工复产的进度会加快，消费者也会保持积极乐观的心态来进行消费活动，消费行为会增多；对于非武汉市市民来说，可以让他们对“武汉”的管理态度进行积极转变，但也可能也会出现如检测收费标准不同而产生不平衡的心理，同时检测也会使外来务工者延误工时、担心出现问题而被隔离或遣返。
3、学生群体复学，上班群体复工复产，老年人群体逐渐恢复日常休闲娱乐活动。主流文化群体会认为进行武汉全员核酸检测是保障居民自身安全的手段，更是为了维护大多数人群的健康。但是亚文化群体可能会认为如果一个人并没有患病，但政府却要求其进行核酸检测，是侵犯了自身人权。
