### ISSUE TITLE
顺丰广告分析

### ISSUE THREAD

**Issue by ELIUAK** [qxnatalie/Learn_ConsumerBehaviour#7]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？

**Comment by Daisy4579** [comment]
消费者的知觉首先来自于消费者的感觉，而顺丰此次的广告在音乐和拍摄风格上有很大的特色，即能够很好地刺激消费者的视觉和听觉。此次顺丰主要想传达的价值是，顺丰可以给家里的老人提供更多的便利，能够给子女一个尽孝的机会和窗口。广告用了很温情的音乐，让人一听就能感受到温暖和平静，产生一种岁月静好的知觉；其次在视觉上，画面的风格也是以暖色调为主，给人以温暖的知觉。这两者结合就能引发大家对自己的父母的感情，从而感受到广告传递的价值。

**Comment by Zhuying000** [comment]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？
  此次的顺丰广告，主要是以一个故事的角度开始，讲述了在外的游子通过顺丰给家里年迈的父母提供便利的服务，尽自己的一份孝心。这主要从消费者的听觉感知和视觉感知方面来触动消费者，塑造了一个充满温情的品牌，同时在这个广告中还传递了顺丰快速、高效、可靠的品牌价值观。

**Comment by ELIUAK** [comment]
UPS在投放刺激信息时主要通过色彩，选择棕色来作为代表颜色，在UPS的快递车，快递员服装等地方加入棕色元素，传达UPS可靠、专业等信息，来引起消费者的注意。而顺丰在香港投放的广告，主要走情感路线，以顺丰帮助在外漂泊的人给他们的父母提供便捷可靠的服务为出发点，从情绪的角度来刺激消费者，顺丰不仅业务能力可靠，带来便捷的服务，更能满足消费者情感上的需求，用温情打动消费者。

**Comment by Sunny893128** [comment]
顺丰的广告是一个在外漂泊的游子给在家的父母提供便利的故事，背景音乐也为非常温情的音乐，主题色调采用暖色，从亲情入手，很好地刺激了消费者的情绪，树立了品牌充满温情，人性化的一面，同时将品牌和亲情捆绑，也突出了顺丰的可靠，故事内容也突出了顺丰的便捷和高效。

**Comment by miracle-qiji** [comment]
消费者知觉是由展露、注意、解释三部分构成。
1、在展露的角度来讲：UPS和顺丰选择的都是selective exposure，UPS主要通过色彩来进行可靠、专业的品牌信息传播，利用服装、快递车等地方渗透到消费者的生活的每个地方。而顺丰则是通过广告，选择性的展露了为年迈父母提供更便捷可靠服务的品牌价值观，所以单从展露来说二者不分伯仲。
2、在注意的角度来讲：二者在刺激物因素方面并无区分，个体因素也大多各凭喜好，只有情景因素是最为重要的一个创意点。顺丰很好的抓住香港地区那个年代年轻人大多外出打工，只有家里的父母老人在家里的年代特征，以情感路线为基础，我认为可以极大的吸引当时香港家有老人的年轻人，成功建立了顺丰亲情的品牌价值文化。
3、在解释的角度来讲：亲情更容易让中国人民产生深的思考，从而探索并了解顺丰真正的品牌。

**Comment by huangyanfang00** [comment]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？
在发展过程中发现不同产业之间关联度比较高，物流与电商紧密相连，而电商产业与电子付费又存在较为紧密的关系。然而，在香港电商与电子付费的普及度与大陆还存在较大差距。这主要是因为一个产业不会单一发展，假如周边产业还没有成熟，比如电商与电子付费尚未普及，那网购就比较麻烦，物流发展也并不顺利。顺丰抓住香港人口老龄化这一特点，在广告中运用温情的感情基调，抒情的音乐和感人的故事下，以此来树立香港消费者心中的传递快速，打破距离界限的品牌形象。

**Comment by xsyAriel** [comment]
消费者知觉过程的第二阶段是注意，影响注意的三个因素分别是：刺激物因素、个体因素和情景因素。USP的广告从颜色、大小、位置等方面传达了品牌专业，可靠的信息，主要利用率刺激物因素，同时将logo印在快递车和快递员的服装上，加强了刺激物对于消费者注意力的吸引。顺丰在香港投放的广告主要利用了情景因素，描绘了了一个儿子回到家看望年老的母亲的情景，利用音乐和画面刺激消费者的视觉和听觉，同时传递了温情和亲情的感情，让消费者在这种时候很容易对照自己的父母，成功吸引消费者的注意。

**Comment by SunYuetHo** [comment]
1、首先是视觉刺激方面。顺丰结合香港社会老龄化的特点，进行有针对性的本土广告投放。广告以孝文化为刺激点，宣传顺丰公司上门取件的贴心服务，帮助老年人完成寄件过程，激起消费者尽孝心的热情。同时广告中提到顺丰公司提供的大件物品例如被子等的储存服务，对应了香港消费者因为房子面积小、大件物品难以储放的痛点，刺激了消费者的情绪，给消费者留下了印象。
2、广告整个画面都是温暖的、阳光的，广告中很多母子对话的内容，让消费者联想到亲情的温暖。与品牌联系起来，塑造起一个接地气、贴心、充满爱与力量的品牌形象。

**Comment by Meacher-P** [comment]
从消费者知觉的角度分析，顺丰广告投放的刺激信息更多的是结合社会现实来实现的视觉冲击。通过画面呈现出来的信息，可以看出香港的职场压抑、社会承担的老龄化压力的现状，其中顺丰塑造了一个便利，有效率，贴心的角色，目标人群是受到家庭和职场双重压力下的人群，传递了顺丰提供便利，服务生活的品牌力量。

**Comment by Perplexeh** [comment]
顺丰投放的广告，主题温暖阳光，抓住了情感这一方面，针对香港老年人独自在家，而顺丰快递能够直接将快递送达的点抓住消费者的眼球。同时，通过音乐和画面刺激消费者，引起消费者的共鸣。其次，通过这种类型的广告，树立了顺丰品牌有人情味，人性化并且贴心的特点，也让更多消费者产生反思，从而选择顺丰。

**Comment by ghost** [comment]
顺丰投放的广告通过抓住消费者的“视觉”和“听觉”，通过暖色调和温馨的音乐创造“温暖”的感觉。针对香港老年人独自在家这一社会现状，顺丰将自己塑造成“子女”进行关心体贴爱护。这种类型的广告给顺丰增添了人情味。结合顺丰品牌本身的高效快速便捷等特点，打造顺丰这一品牌物质基础+情感价值。

**Comment by Woaxuex** [comment]
从消费者知觉过程第二阶段注意的刺激性因素分析：UPS投放的刺激信息运用颜色、大小、位置的因素，通过快递员服装和快递车外观，向消费者传递可靠、专业、值得信任的品牌形象。顺丰投放的刺激信息则运用色彩、运动、有趣性和信息量等因素，以亲情为核心，通过打造消费场景，向消费者传递温暖、贴心、服务好的品牌形象。

**Comment by Riley-Ai** [comment]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？
消费者知觉过程的第二阶段是注意，影响注意的三个因素分别是：刺激物因素、个体因素和情景因素。USP的广告从颜色、大小、位置等方面传达了品牌专业，可靠的信息，主要利用率刺激物因素，同时将logo印在快递车和快递员的服装上，加强了刺激物对于消费者注意力的吸引。顺丰在香港投放的广告主要抓住了情感这一方面，针对香港老年人独自在家，而顺丰快递能够直接将快递送达的点抓住消费者的眼球。同时，通过音乐和画面刺激消费者，引起消费者的共鸣。

**Comment by Fairy-teng** [comment]
这个广告讲述在外的年轻人给父母送温暖通过顺丰这个平台，背景音乐感人，引导人进入这种氛围，色调温和，很好地刺激了消费者的情绪，树立了品牌充满温情。既体现了顺丰配送速度快的特点，也加了更多人性化因素在里面，引起消费者的共鸣，而且如果消费者遇到同样的问题，需要给家人寄东西，第一反应也会是选择顺丰快递。

**Comment by qiudi666** [comment]
UPS广告主要通过代表色、服饰、快递车等刺激信息，引起消费者的注意，向消费者传达专业、严肃、可靠等品牌价值观。而顺丰在本广告中以情景因素为主，通过描述一位常年闯荡在外的儿子借助顺丰的服务孝顺老母亲的故事，利用听觉和视觉感官，贴合了香港老龄化的社会现状，使消费者产生了自发性解释行为，刺激了消费者渴望尽孝的心理，与消费者产生情感共鸣，传达了品牌温暖、贴心、快捷的重要价值。

**Comment by xiaowuastro** [comment]
usp的广告比较注重外在，比如色彩，棕色让人们对其有更为信任的感觉，但是顺丰不同，它主要是满足人们的心理需求，针对 老龄化严重的问题还有空巢老人问题，以温馨的氛围来打动消费者内心的感情世界，更能引起消费者的内心共鸣。形成情感依赖

**Comment by Wly-Mercury** [comment]
消费者知觉过程第二阶段注意的刺激性因素刺激物因素、个体因素和情景因素。UPS投放的刺激信息运用颜色、大小、位置的因素，通过快递员服装和快递车外观，向消费者传递可靠、专业、值得信任的品牌形象。顺丰投放的刺激信息则运用色彩、运动、有趣性等因素，描绘了一个儿子回到家看望年老的母亲的情景，利用音乐和画面刺激消费者的视觉和听觉，以亲情为核心，向消费者传递温暖、贴心、服务好的品牌形象。

**Comment by Asuracch** [comment]
从消费者知觉的角度分析，顺丰投放的广告通过抓住消费者的“视觉”和“听觉”，通过暖色调和温馨的音乐创造“温暖”的感觉。广告讲述在外的年轻人给父母送温暖通过顺丰这个平台服务孝顺老母亲的故事，抓住情感这一方面，针对香港老年人独自在家的社会现状，刺激了消费者渴望尽孝的心理，与消费者产生情感共鸣，传达了品牌温暖、贴心、快捷的重要价值。

**Comment by double-L666** [comment]
消费者知觉在顺丰广告中主要体现在以”视觉“和”听觉“来打造温情，通过孝顺为情感故事线，使消费者产生共鸣，给人一种安心，踏实的品牌形象。而UPS则以直观的视觉效果，给消费者展示出自己专业，可靠的品牌形象。

**Comment by yuan-akemam** [comment]
顺丰的广告主要从“视觉”和“听觉”两个方面来触动消费者的内心，通过“孝”这一中华民族传统美德的精神，来打造一个温暖，贴心的品牌。而UPS主要“视觉”为主，通过褐色和黄色的对比来表达自己专业高效，稳定可靠的特点。

**Comment by littlePeppapig** [comment]
在认识过程中，消费者不仅借助感觉器官对商品的个别属性进行感受，而且能将个别属性联系起来，进行整体反映。这种人脑对直接作用于感觉器官的客观事物个别属性的整体反映，就是知觉。消费者知觉的选择，首先源于感觉阈限，顺丰投放的刺激信息呈现的画面和配乐首先抓住了消费者的视觉和听觉，引起大众的关注。其次信息主题源于生活，易于消费者感知和理解，并且符合消费者需要、价值观、能够让消费者产生明显好感和认同感，引发共鸣。整体概念与品牌的特质和内涵相契合，让消费者接触信息的过程中将产生的感受与品牌结合起来，从而塑造品牌的整体形象，获得价值的提升。

**Comment by bubbleCC** [comment]
ups使用了刺激物因素，从大小、色彩来说，logo的棕色给人沉稳的感觉，出现的快递员服装也在传递安全稳定的知觉，顺丰采用了情境因素，调动了消费者观看视频时的情绪，传递了温情，达到绝对感觉阈限为消费者所感知。

**Comment by bubbleCC** [comment]
ups使用了刺激物因素，从大小、色彩来说，logo的棕色给人沉稳的感觉，出现的快递员服装也在传递安全稳定的知觉，顺丰采用了情境因素，调动了消费者观看视频时的情绪，传递了温情，达到绝对感觉阈限为消费者所感知。

**Comment by bubbleCC** [comment]
ups使用了刺激物因素，从大小、色彩来说，logo的棕色给人沉稳的感觉，出现的快递员服装也在传递安全稳定的知觉，顺丰采用了情境因素，调动了消费者观看视频时的情绪，传递了温情，达到绝对感觉阈限为消费者所感知。

**Comment by 113114106** [comment]
ups投放的广告与顺丰的风格和侧重点不同。
在ups中，采用刺激物因素，用大量的棕色以彰显ups稳定安全的特性。而顺丰更倾向于情景因素，通过打造在外游子通过顺丰来关怀老人的情景来刺激人们的情感，引起人的共情，从而使消费者对顺丰留下深刻印象。

**Comment by Akakiyoe** [comment]
从消费者知觉的角度分析：UPS投放的广告，侧重以刺激物因素，来传达安全可靠，专业放心的形象与特点。而顺丰投放的广告的刺激物信息则是运用各类现实情境因素，从亲情这一角度出发，来向消费者传达自身温暖、贴心的品牌形象。

**Comment by little-moom** [comment]
此次的顺丰广告，从视觉和听觉两方面来刺激消费者。整个广告走情感路线，讲述了漂泊在外的游子通过顺丰为年迈的父母提供贴心服务的故事，配合温暖的BGM，使整个广告充满人情味。不仅体现了顺丰的可靠、便利，更凸显了顺丰情感情感桥梁的作用，从情感打动消费者。

**Comment by akabula** [comment]
这次的顺丰广告，从视觉和听觉两方面来刺激了消费者：
1.视觉：UPS在视觉上主要通过色彩，选择棕色来作为代表颜色，在UPS的快递车、快递员服装等方面使用棕色，让消费者感受到UPS的可靠、专业。而顺丰在视觉上通过在香港投放广告，主要走情感路线，表达顺丰能够帮助在外漂泊的人给他们的父母提供便捷可靠的服务，无论是从拍摄的手法还是广告的色调，都能让观众感受到温暖、感动。
2.听觉：顺丰拍摄的广告是有背景音乐的，音乐与广告故事相辅相成，达到了更好的效果。

**Comment by Tiantian-Wu** [comment]
顺丰在香港投放的广告，结合香港社会老龄化的特点，进行有针对性的本土广告投放，主要走情感路线，以顺丰帮助在外漂泊的人给他们的父母提供便捷可靠的服务为出发点，在视觉上，画面的风格也是以暖色调为主，给人以温暖的感觉，在听觉上，背景音乐舒缓而温馨，向消费者传递温暖、贴心、服务好的品牌形象。

**Comment by Ashley-SKY** [comment]
UPS侧重刺激物因素，在视觉上选择棕色来作为代表颜色，在UPS的快递车、快递员服装等方面使用棕色，让消费者感受到UPS的可靠、专业。而顺丰投放香港广告主要走情感路线，在老龄化背景下联系亲情，听觉上广告的BGM温暖人心，在视觉场景和拍摄手法上突出顺丰能够帮助在外的游子给他们年迈的父母提供便捷可靠的服务，尽自己的一份孝心。塑造了顺丰便捷高效又人性化的形象。

**Comment by bulebuleaa** [comment]
消费者知觉分为三个部分：展露、主义和解释。UPS和顺丰的广告的区别主要在第二和第三部分。
UPS侧重通过刺激物因素来引起消费者知觉，使用棕色作为代表色，传达出可靠、专业、可信赖的理念，让消费者理解认知。
顺丰则选择运用情境因素，广告讲述了在外工作的年轻人选择用顺丰为年迈的父母送温暖的故事，这个故事联系了当下老龄化的背景，关爱空巢老人，体现了“孝文化”，让消费者感受到出顺丰品牌的快捷可靠，传达了顺丰贴心温暖的服务信息。

**Comment by Wuxintian** [comment]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？
UPS主要从视觉（颜色，形状，构图等）刺激消费者来传达其品牌价值，而顺丰在香港所投放的广告，以视觉，听觉两方面传递其品牌价值。视频广告简述了一个故事，结合香港老龄化趋势的情景，以符合“孝”文化的剧情，引起消费者的情感共鸣；视频背景音乐也能传递一种温馨的感觉。塑造出顺丰温暖，人性，服务好的品牌价值。

**Comment by MingPeng67** [comment]
从消费者知觉的角度分析，这次顺丰在香港投放的广告，具有针对性，从视觉和听觉两方面，营造温情的氛围，触动观者的心弦，从而引起共鸣，树立顺丰贴心、可信赖的形象。而UPS从颜色视觉出发，塑造出UPS专业、可靠的形象。

**Comment by double-cloud** [comment]
UPS通过在快递车，快递员服装等加入棕色元素，传达出UPS专业可靠、稳重、值得信赖的信息。
而顺丰则是利用视觉、听觉营造了一种温暖的氛围，讲述了一个故事，帮助独居的父母，与在外打拼的用户形成共鸣，传达顺丰可靠、温暖、为您服务的价值观。

**Comment by ymandlsy** [comment]
从消费者知觉的角度来看，UPS主要是通过抓住消费者的视觉因素，通过标志上的棕色色彩来向消费者传达出其安全、可靠的特点。
而顺非在香港投放的广告则是刺激了消费者的视觉和听觉，通过一个完整的故事，不仅使得顺非温暖、服务周到、关爱消费者的形象特点深入人心，还同时加深了消费者对顺非的印象，不会迅速的遗忘。

**Comment by CXHHHHHHH** [comment]
UPS以棕色为代表色，向消费者传达专业、稳重、可靠的形象。顺丰的广告针对香港老龄化程度较高的特点，选择以空巢老人的情境为切入点，以细致周到的服务为在外打拼的游子照顾好家中的老人，营造出温暖、贴心的品牌形象。

**Comment by congyi0828** [comment]
从消费者知觉的角度看，ups选择了代表沉稳可靠的棕色作为主色调，利用视觉信息将自己的企业理念传递给消费者；而顺丰利用视觉和听觉讲述了一个温情的故事，结合香港老龄化的趋势，传递“孝”的理念，营造出自己温情、便捷的形象。

**Comment by whatffan** [comment]
ups投放的广告与顺丰的侧重点不同。
在ups的广告中，采用刺激物因素，在快递车和工作服中加入大量棕色来塑造ups稳重、可靠、专业的形象。而顺丰更倾向于情景因素，针对香港社会老龄化的趋势，讲述了顺丰帮助在外漂泊的人给他们的父母提供便捷可靠的服务，引发消费者的情感共鸣，给消费者留下安心、用心、放心的形象

**Comment by promisecret** [comment]
ups以棕色为主调，从视觉上向消费者传达稳重放心的形象。顺丰则是视听结合，与香港老龄化趋势呼应，体现了“孝”的主题，营造温暖氛围，给消费者以留下温情形象。

**Comment by Leona-2000** [comment]
从消费者的知觉出发，顺丰广告首先用较为温暖、平和的棕色来向消费者传达品牌的可靠形象，再用温情的音乐来刺激消费者听觉，用温情的故事情节从视觉上向消费者传达顺丰可靠、高效、有人情味的品牌形象。

**Comment by lanjinhua** [comment]
从消费者的知觉角度分析，顺丰在香港投放的广告将消费者带到一个特定的情境当中，引起消费者共鸣，刺激消费者的知觉。温暖的背景音乐，暖色调的画面，在外漂泊的游子通过顺丰给年老的父母提供优质的服务。传递温情，服务生活的形象深入人心。

**Comment by Faolan-SY** [comment]
UPS广告中整个背景的色调以棕色为主，强调了UPS的可靠与值得信任，而顺丰在香港投放的广告中主要采用暖色调，更是融入了儿子与母亲的故事，传递了孝道的精神，使得顺丰多了一些温情与生活的气息。

**Comment by Tkaneshiro1874** [comment]
ups的广告主要用了颜色、品牌标志、快递车、快递员等外在元素，向消费者传递专业可靠的品牌形象。相比ups，顺丰的广告是结合社会现实情景给受众带来刺激信息。广告中顺丰帮助了在外工作的儿子孝敬母亲，正好击中了香港空巢老人和老龄化的社会痛点，配合温馨的画面和音乐，能引起许多人情感共鸣。

**Comment by daisy996-create** [comment]
UPS的广告通过色彩、快递员的服装等刺激信息向消费者展现了品牌专业安全可靠的形象。而顺丰则讲述了一个年轻人通过顺丰平台孝顺父母的故事，从视觉和听觉两个方面刺激消费者，向消费者展现了一个温暖、快捷的品牌形象，激发了消费者的情感共鸣。

**Comment by calmbalalanl** [comment]
从消费者知觉的角度分析：对比UPS，顺丰在香港投放刺激信息是如何塑造品牌价值的？
消费者知觉是消费者借助 感觉器官对商品的个别属性进行整体感受，而且能将各个个别属性联系、综合起来、进行整体反映。ups广告从视觉出发，以棕色为主，为消费者描述出一个温暖、稳重、可靠的形象。而顺丰广告采用试听结合的方式，将一个在外漂泊游子，通过顺丰为家乡父母提供优质生活的故事，娓娓道来。营造温暖、贴心、便捷、可靠的品牌形象

**Comment by WangYxxx** [comment]
消费者知觉过程的第二阶段是注意，影响注意的三个因素分别是：刺激物因素、个体因素和情景因素。
USP的广告从颜色、大小方面传达了品牌信息，首先利用视觉刺激因素，将logo印在快递车和快递员的服装上，加强了刺激物对于消费者注意力的吸引。顺丰在香港投放的广告主要抓住了情感刺激这一方面，针对香港老年人独自在家，通过音乐和画面刺激消费者，引起消费者的共鸣。

**Comment by Happy-deep** [comment]
USP主要通过色彩、形状等突出视觉刺激的刺激性因素吸引消费者的注意。将品牌logo印在鲜艳的快递车以及快递服装上，将视觉刺激因素最大化展露给消费者。
顺丰的广告主要是用情境因素吸引消费者的注意，广告中通过音乐和画面色营造温馨的情景，引起消费者对亲情的共鸣，顺利将顺丰速递洗衣贴心，方便的特点植入到消费者心中。

**Comment by DR-ng** [comment]
从消费者知觉的角度来看，UPS主要利用了刺激性因素，例如通过不断出现的品牌标志，色彩，快递车等因素，向消费者传递专业可靠、稳重，值得信赖的品牌形象。而顺丰则是更多利用情景因素，结合香港老龄化的社会现状，呈现了在外的年轻人通过顺丰向家中年老父母传递关爱与温暖这样的故事，用此情境带动消费者的情绪，从而传递顺丰温情、可靠、充满爱的品牌形象。

**Comment by yeahhuinim** [comment]
UPS主要是通过鲜明的色彩与显眼的logo不断的给消费者带来视觉上的刺激性作用，在各个方面吸引消费者的眼球，将UPS的品牌形象最直观的展示给大众。
顺丰在香港的广告，则主要是通过给消费者带来情感上的刺激，主打亲情路线。通过对香港社会环境中存在的老龄化问题的关注，一方面提醒社会大众对老年人群的关注，另一方面更重要的是凸显了顺丰的快速、可靠。

**Comment by nonono-123** [comment]
UPS主要是通过刺激物的颜色大小和布局给消费者带来强烈的视觉刺激，从而引发其兴趣进而对UPS产生一个记忆点。
而顺丰广告着重于场景化的代入，通过构建温情的场景引发消费者的感情共鸣，在无形中传达给消费者顺丰安全可靠便利、有人文关怀的品牌形象。

**Comment by daisy1217264** [comment]
在发展过程中发现不同产业之间关联度比较高，物流与电商紧密相连，而电商产业与电子付费又存在较为紧密的关系。然而，在香港电商与电子付费的普及度与大陆还存在较大差距。这主要是因为一个产业不会单一发展，假如周边产业还没有成熟，比如电商与电子付费尚未普及，那网购就比较麻烦，物流发展也并不顺利。顺丰抓住香港人口老龄化这一特点，在广告中运用温情的感情基调，抒情的音乐和感人的故事下，以此来树立香港消费者心中的传递快速，打破距离界限的品牌形象。

**Comment by Rena-99** [comment]
UPS广告主要通过代表色、服饰、快递车等刺激信息，引起消费者的注意，向消费者传达专业、严肃、可靠等品牌价值观。而顺丰更有人情味，落脚在空巢老人的问题，以温情来打动消费者，与消费者建立情感联系，更能给消费者留下印象，引起大众关注，扩大宣传，塑造品牌形象，提升品牌价值。

**Comment by addition-nzr** [comment]
USP广告主要在外观方面着手，注重塑造品牌的外在形象，利用不同的颜色打造一款负责任的品牌形象；而顺丰物流更具有人文关怀的属性，通过对社会主要问题的敏锐观察并给出个性化的解决方案来吸引用户群体的注意。顺丰通过关爱空巢老人，关心弱势群体来解决社会性难题，既体现了企业的经济效益，又追求了社会效益，展现了企业的责任担当，更易于赢得消费者的关注和信任，更利于提升品牌价值内涵和企业形象。

**Comment by Maeve727** [comment]
从消费者知觉的角度分析，顺丰广告通过整体的暖色调和温馨舒缓的音乐，抓住了消费者的视觉和听觉。以亲情为主题，在外漂泊的人给在家的父母提供便利可靠的服务，打动消费者。成功树立快速、可靠、温情的品牌形象，获得消费者的信任和选择。

**Comment by Rchentan** [comment]
UPS的广告利用颜色这一视觉刺激，用棕色的设计给消费者以安全可靠，专业认真之感，吸引消费者信任并选择UPS。
顺丰的广告则利用了情景刺激，描述了年长的父母通过顺丰获取便捷服务，刺激在外工作，无法时时照顾父母的年轻人对于赡养父母的心态，用感情打动消费者，从而选择顺丰。

**Comment by Jegelsker** [comment]
消费者知觉主要是客观事物直接作用于感官在头脑中产生的对事物的整体认知。UPS快递的广告主要强调自己的专业性，通过色彩和响亮的口号让消费者通过眼睛和耳朵将UPS的专业性记住。顺丰在香港投放的广告主要描述了年轻人在外打拼，老年人独自在家，顺丰能将快递送至这些老年人手上，顺丰将自己放在了“子女”的位置上，通过亲情这一点引起消费者的情感共鸣，从而达到打动消费者的效果。

**Comment by Lannister424** [comment]
顺丰投放的刺激信息则运用色彩、运动、有趣性和信息量等因素，主色使用暖色调，以亲情为核心，通过打造消费场景，向消费者传递温暖、贴心、服务好的品牌形象。
UPS投放的刺激信息运用颜色、大小、位置的因素，在刺激因素的选择上差别不大，它更偏向于使用冷色调，利用快递员服装和快递车外观，向消费者传递可靠、专业、值得信任的品牌形象。

**Comment by XiangYe0392** [comment]
消费者知觉过程的第二阶段是注意，影响注意的三个因素分别是：刺激物因素、个体因素和情景因素。
UPS的用沉稳大气的棕色、专业的快递工作人员及运输工具来传递其安全、可靠、专业的品牌形象；
顺丰的广告则用温馨的电影画面、温情的故事内容、温暖的配乐与色调，以亲情为主要传递内容，打造令消费者舒心的消费场景，传递了其温馨、贴心、放心的品牌形象。

**Comment by IRIS-LI00** [comment]
运用消费者知觉因素进行传播，USP的广告侧重颜色，大小，位置因素来刺激消费者，运用冷色调表达自身专业可靠的形象，塑造品牌个性，让消费者印象深刻。顺丰则采用一则远在外地的游子对母亲的关心，利用音乐和画面让消费者产生情感的共鸣，在配色和配乐上都选用温暖的元素，突出顺丰温暖贴心的形象，使得消费者印象深刻

**Comment by chen-hao-nan** [comment]
UPS的广告运用颜色、大小、位置的因素刺激消费者，向消费者传达专业、严肃、可靠等品牌价值观。顺丰通过孝这一主题，结合暖心配色与音乐，来体现顺丰温馨，高效，可靠的特点，让消费者信任顺丰，选择顺丰。
