### ISSUE TITLE
讨论题：制定营销策略和方案，传递“I can’t breathe ”口号的价值

### ISSUE THREAD

**Issue by ELIUAK** [qxnatalie/Learn_ConsumerBehaviour#8]
讨论题：最近美国种族歧视矛盾加剧，“I can’t breathe ”口号声势浩大。请结合“学习和记忆”内容，制定出相应营销策略和方案将此口号传递的价值持续到下半年“特不靠谱”竞选连任。

**Comment by ELIUAK** [comment]
“一起铺花路吧”小组
成员：田钰 任颖 张茜 吴泉泳 叶芳娴
策划文案：[I can breathe.pdf](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840245/I.can.breathe.pdf)
宣传视频：
[I can breathe.zip](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840268/I.can.breathe.zip)

**Comment by qiudi666** [comment]
成员：张佳慧 仰梦姣 邱笛
活动阐述+海报展示：
[“I can't breathe.”×天气--张佳慧 仰梦姣 邱笛.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840456/I.can.t.breathe.x.--.docx)

**Comment by Ruby0408** [comment]
成员：陈思懿 程正卓 韩丹 余瑞彬
策划文案+LOGO：
[“YOU ARE FIRED”.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840759/YOU.ARE.FIRED.docx)

**Comment by calmbalalanl** [comment]
成员：陈思懿 程正卓 韩丹 余瑞彬
策划文案+LOGO：
[“YOU ARE FIRED”.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840758/YOU.ARE.FIRED.docx)

**Comment by huangyanfang00** [comment]
[
[i can't breath.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840775/i.can.t.breath.docx)
](url)

**Comment by ghost** [comment]
成员：唐维杰、李秀湄、胡剑锋、丁蓉
自制视频广告+策划案（简）
[I can't breathe.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4840943/I.can.t.breathe.docx)
（由于不支持视频文件，广告视频采用私聊发送的方式给了老师）

**Comment by Maeve727** [comment]
1

**Comment by Maeve727** [comment]
[

**Comment by Maeve727** [comment]
[](url)
[I can't breathe！.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4841700/I.can.t.breathe.docx)

**Comment by Woaxuex** [comment]
成员：梁广治、明鹏、兰金花、李禹嫣、李靖仪、李佳慧
传播方案+创意呈现：
[I can.t breathe 传播方案.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4841805/I.can.t.breathe.docx)

**Comment by double-L666** [comment]
营销1801邹世龙
宣传视频+策划案
[营销1801邹世龙.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4841966/1801.docx)
宣传视频以私法形式发送给老师。

**Comment by double-L666** [comment]
宣传视频+策划案
[营销1801邹世龙.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4841969/1801.docx)
宣传视频以私法形式发送给老师。

**Comment by double-L666** [comment]
宣传视频+策划案
[营销1801邹世龙.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4841972/1801.docx)
宣传视频以私发形式发送给老师。

**Comment by Tkaneshiro1874** [comment]
成员：熊诗怡 钟婕 朱颖 左乐 谭宇晴
活动方案+海报展示
[秋名山车队-I can't breathe.pdf](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4842463/-I.can.t.breathe.pdf)

**Comment by Meacher-P** [comment]
[I can't breathe设计.pptx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4842508/I.can.t.breathe.pptx)

**Comment by Lannister424** [comment]
[“I can’t breathe ”I can’t forget.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4842556/I.can.t.breathe.I.can.t.forget.docx)
上传了半天，上传不进去

**Comment by Faolan-SY** [comment]
1.设计一款关于“I can’t breathe ”的衣服，并邀请知名人物进行宣传。
2.创办名为“I can’t breathe”的组织，定期举办游行。
3.创办“I can’t breathe”的刊物，定期邀请知名作家投稿文章。
4.邀请口罩厂商生产印有“I can’t breathe”的口罩。

**Comment by congyi0828** [comment]
成员：张聪逸、王逸凡
[
[I can’t breathe.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4843215/I.can.t.breathe.docx)
](url)

**Comment by congyi0828** [comment]
成员：张聪逸、王逸凡
[I can’t breathe.docx](https://github.com/qxnatalie/Learn_ConsumerBehaviour/files/4843217/I.can.t.breathe.docx)
